### ISSUE TITLE
Upload the extension to Chrome Web Store

### ISSUE THREAD

**Issue by CarolHsu** [xatier/tauphahji-lookup#1]
I found this extension so fascinating and it ought to be uploaded to the [Chrome Web Store](https://chromewebstore.google.com/). Lord please save us from tâi-lô á, Amen.

**Comment by xatier** [comment]
Unfortunately, I do not have a Google dev account, which takes some annoying process to set up, including paying Google $5 [1]. I would suggest clone the repo and load the extension locally instead.

[1] https://developer.chrome.com/docs/webstore/register
